apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
data:
  RabbitMQ__Host: "amqp://rabbitmq-services"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
  MongoDb__LocalConnectionString: "mongodb://mongodb-service"
  MongoDb__DatabaseName__BookStore: "BookStore"
