apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-notification-app-deployment
spec:
  replicas: 2 # increase the number of replicas to increase the speed of the notification
  selector:
    matchLabels:
      app: notification-service-app
  template:
    metadata:
      labels:
        app: notification-service-app
    spec:
      containers:
      - name: notification-service
        image: nghialoe/notification-service:latest
        ports:
        - containerPort: 80
        env:
        - name: RabbitMQ__Host
          value: "amqp://rabbitmq-service"
        - name: RabbitMQ__Username
          value: "guest"
        - name: RabbitMQ__Password
          value: "guest"
        - name: MongoDb__LocalConnectionString
          value: "mongodb://mongodb-service"
          name: MongoDb__DatabaseName__BookStore
          value: BookStore
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-lb
spec:
  selector:
    app: notification-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
