apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-notification-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service-app
  template:
    metadata:
      labels:
        app: notification-service-app
    spec:
      containers:
      - name: notification-service
        image: nghialoe/notification-service:latest
        ports:
        - containerPort: 80
        env:
        - name: RabbitMQ__Host
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: RabbitMQ__Host
        - name: RabbitMQ__Username
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: RabbitMQ__Username
        - name: RabbitMQ__Password
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: RabbitMQ__Password
        - name: MongoDb__LocalConnectionString
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: MongoDb__LocalConnectionString
        - name: MongoDb__DatabaseName__BookStore
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: MongoDb__DatabaseName__BookStore
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-lb
spec:
  selector:
    app: notification-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer